### ISSUE TITLE
[BUG] *Doesn't work as intended*

### ISSUE THREAD

**Issue by NandeUwU** [Splarkszter/Splarkszter-AutoFish#4]
#### Tasks
- [ ] I have AutoHotKey installed on my system
- [ ] I have searched for other issues with the same problem
- [ ] I have read the [**How to use**](https://github.com/Splarkszter/Splarkszter-AutoFish#how-to-use) in the main README.md

#### Description
A clear and concise description of what the issue is about.

#### To Reproduce
Include the steps to reproduce the behavior.

**Comment by Splarkszter** [comment]
Try disabling chromatic aberration... the script looks for pixel color change so if you move, it will activate.

If you keep having problems keep disabling graphical settings that make the rod move or change colors. You need to stand perfectly still (or at least not rotate).
